# -*- coding: utf-8 -*-
"""Z SCORE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q8ohqAK-7zmyXPL9-Cg-0B5cRL6Y3_dO
"""

import numpy as np
import pandas as pd
import scipy.stats as stats

"""step 1: Import modules
step 2: create an arrays of values
"""

data = np.array([2,4,6,89,4,56,7,12,44,22,23,16])

"""step 3: calculate the z-score for each value in the array."""

stats.zscore(data)